import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import apiClient from '../api';
import { findFilmByTitleRequest, useFindFilmByTitleQuery } from '../hooks';
import styles from '../styles/Home.module.css';
import { Film } from '../types';

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await findFilmByTitleRequest('Harry Potter');

  return {
    props: {
      film: response.data,
    }, // will be passed to the page component as props
  };
};

type Props = {
  film: Film;
};

const ServerRender: NextPage<Props> = (props) => {
  // Data fetched on client-side

  // You should see this data output in the console, which means that the data is being fetched on the server-side
  // as opposed to the client-side
  console.log(props.film);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Server rendered</h1>
      </main>
    </div>
  );
};

export default ServerRender;
